blog/urls.py
from django.contrib import admin
from django.urls import path
from ui.views import *
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePage.as_view(), name = "home-page"),
    path('blog/<slug>', BlogDetail.as_view(), name="blog-detail"),
    path('login', Login.as_view(), name="login"),
    path('update/blog', UpdateBlog.as_view(), name="update-blog"),
    path('edit/blog/<id>', UpdateBlogApi, name="edit-blog-api"),
    path('logout', Logout.as_view(), name="logout")
]

ui/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Blog(models.Model):
	image = models.FileField(upload_to="static/images", unique= True, null=True, blank=True)
	title = models.CharField(max_length=255, null=True, blank=True)
	short_content = models.CharField(max_length=255, null=True, blank=True)
	content = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

	def __str__(self):
		return str(self.title)

ui/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
User = get_user_model()

class BlogForm(forms.ModelForm):

	class Meta:
		model = Blog
		fields = "__all__"

	title = forms.CharField(
		required = True,
		widget=forms.TextInput(
			attrs={
			'type': 'text',
			'class': 'input rounded px-4 mb-3 py-2',
			'placeholder': 'Title blog *',

			}
			)
		)
	short_content = forms.CharField(
		required = True,
		widget=forms.Textarea(
			attrs={
			'type': 'text',
			'class': 'input short-content-input rounded px-4 mb-3 py-2',
			'placeholder': 'Short content blog *'
			}
			)
		)
	content = forms.CharField(
		required = True,
		widget=forms.Textarea(
			attrs={
			'type': 'text',
			'class': 'input rounded px-4 mb-3 py-2',
			'placeholder': 'Content blog *'
			}
			)
		)

class LoginForm(AuthenticationForm):
	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in self.fields.values():
			field.widget.attrs['class'] = 'rounded border-0 mb-3 p-2 w-100 input-login w-100 text-main'
			field.widget.attrs['placeholder'] = field.label

ui/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, DetailView
from .models import *
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from . import forms
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy

# Create your views here.
User = get_user_model()

class HomePage(ListView):

	model = Blog
	template_name = "home/home.html"
	context_object_name = "blog"

	def  get_queryset(self):

		blog = Blog.objects.all().order_by('-created_at')
		return blog;

class BlogDetail(DetailView):

	model = Blog
	template_name = "blog/blog-detail.html"
	context_object_name = "blogDetail"

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		slug = self.kwargs.get('slug')
		context['blogRelated'] = Blog.objects.exclude(id=slug)[:3]
		return context

	def get_object(self, **kwargs):
		slug = self.kwargs.get('slug')
		blog = Blog.objects.filter(id=slug).first()
		return blog

class UpdateBlog(LoginRequiredMixin, TemplateView):
	template_name = "blog/update-blog.html"
	form_class = forms.BlogForm

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		context['form'] = self.form_class()
		context['blog'] = Blog.objects.all().order_by('-created_at')
		return context

	def post(self, request, *args, **kwargs):
		context = self.get_context_data(**kwargs)
		form = self.form_class(self.request.POST, request.FILES)
		if request.POST.get('form_type') == "create":
			if form.is_valid():
				blog = form.save(commit=False)
				blog.user = request.user
				blog.save()
			else:
				context['form'] = form

		if request.POST.get('form_type') == "delete":
			id = request.POST.get('id_blog')
			blogDetail = Blog.objects.filter(id=id).first()
			if request.user == blogDetail.user:
				blogDetail.delete()
				context['message'] = "Delete success"
			else:
				context['message'] = "Do not have permission to delete"

		if request.POST.get('form_type') == "edit-submit":
			id = request.POST.get('id')
			blogDetail = Blog.objects.filter(id=id).first()
			if request.user == blogDetail.user:
				if form.is_valid():
					blog = form.save(commit=False)
					blogDetail.image = form.cleaned_data['image']
					blogDetail.title = form.cleaned_data['title'] 
					blogDetail.short_content = form.cleaned_data['short_content']
					blogDetail.content = form.cleaned_data['content']
					blogDetail.user = request.user
					blogDetail.save()
					context['message'] = "update success"
				else:
					context['message'] = "update fail"
			else:
				context['message'] = "do not have permission to update"
		return self.render_to_response(context)

def UpdateBlogApi(request, id):
	if request.method == "GET":
		try:
			blogDetail = Blog.objects.filter(id=id).first()
			if blogDetail is not None:
				blog_data = {
                    "id": blogDetail.id,
                    "image": blogDetail.image.url,
                    "title": blogDetail.title,
                    "short_content": blogDetail.short_content,
                    "content": blogDetail.content
                }
				return JsonResponse({'context': blog_data})
		except Exception as e:
			return HttpResponseBadRequest({'Invalid request',e })
	return HttpResponseBadRequest('Invalid request 1')
	
class Login(LoginView):
	form_class = forms.LoginForm
	template_name = "login/login.html"

	def get_success_url(self):
		return reverse_lazy('update-blog')

class Logout(LogoutView):
	def get_success_url(self):
		return reverse_lazy('home-page')
	



	

ui/templates/blog/blog-detail.html
{% extends 'layout.html'%}
{% block title %} blog detail {% endblock %}
{% load static %}
{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/blog.css'%}">
{% endblock %}
{% block content %}
<!-- banner -->
<div>
    <img src="https://nhatrangnow.com/wp-content/uploads/2022/05/PicsArt_08-25-09.22.38.jpg" class="banner">
</div>
<div class="container py-5">
    <div class="container-content-blog p-3 mb-4">
        <div class="mb-2">
            <b class="title-detail-blog">{{ blogDetail.title }}</b>
        </div>
        <div>
            {{ blogDetail.content|safe }}
        </div>
    </div>
    <div class="container-blog-related">
        <div class="d-flex justify-content-between align-items-center mb-2">
            <b>Blog liên quan</b>
        </div>
        <div class="row">
            {% if blogRelated|length > 0 %}
            {% for item in blogRelated %}
            <div class="col-4 pb-3">
                <div class="container-blog h-100 d-flex flex-column">
                    <div>
                        <img src="/{{ item.image }}" class="w-100 img-blog">
                    </div>
                    <div class="p-2 d-flex flex-column justify-content-between flex-fill">
                        <div>
                            <a href="{% url 'blog-detail' item.id %}">
                                <h1>{{ item.title }}</h1>
                            </a>
                            <div class="text-right">{{ item.created_at }}</div>
                            <div class="short-content mb-2">
                                <span>{{ item.short_content}}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-4 pb-3">
                <div class="container-blog h-100 d-flex flex-column">
                    <div>
                        <img src="https://nhatrangnow.com/wp-content/uploads/2022/05/PicsArt_08-25-09.22.38.jpg" class="w-100 img-blog">
                    </div>
                    <div class="p-2 d-flex flex-column justify-content-between flex-fill">
                        <div>
                            <h1>Kinh nghiệm đi du lịch nha trang</h1>
                            <div class="text-right">18/03/2024</div>
                            <div class="short-content mb-2">
                                <span>Kinh nghiệm đi du lịch nha trang giành cho bạn, Kinh nghiệm đi du lịch nha trang giành cho bạn </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4 pb-3">
                <div class="container-blog h-100 d-flex flex-column">
                    <div>
                        <img src="https://nhatrangnow.com/wp-content/uploads/2022/05/PicsArt_08-25-09.22.38.jpg" class="w-100 img-blog">
                    </div>
                    <div class="p-2 d-flex flex-column justify-content-between flex-fill">
                        <div>
                            <h1>Kinh nghiệm đi du lịch nha trang</h1>
                            <div class="text-right">18/03/2024</div>
                            <div class="short-content mb-2">
                                <span>Kinh nghiệm đi du lịch nha trang giành cho bạn, Kinh nghiệm đi du lịch nha trang giành cho bạn </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

ui/templates/blog/update-blog.html
{% extends 'layout.html' %}
{% block title %} Update blog {% endblock %}
{% load static %}
{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/update-blog.css'%}">
{% endblock %}
{% block content %}
<div>
    <div class="row mx-0">
        <div class="col-3">Menu left</div>
        <div class="col-9 pt-5 px-0">
            <div class="mb-3 ms-3">
                <button onclick="createBlog()" class="btn btn-danger" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">+ Create</button>
            </div>
            <div class="text-center">
                {% if message %}
                <p>{{message}}</p>
                {% endif %}
            </div>
            <div class="row mx-0 pe-5">
                {% for item in blog %}
                <div class="col-4 pb-3">
                    <div class="container-blog h-100 d-flex flex-column">
                        <div class="position-relative">
                            <img src="/{{item.image}}" class="w-100 img-blog">
                            <div class="d-flex gap-3 position-absolute bg-white top-0 end-0 p-2">
                                <div>
                                    <a href="{% url 'blog-detail' item.id %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                            <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8M1.173 8a13 13 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5s3.879 1.168 5.168 2.457A13 13 0 0 1 14.828 8q-.086.13-.195.288c-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5s-3.879-1.168-5.168-2.457A13 13 0 0 1 1.172 8z" />
                                            <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0" />
                                        </svg>
                                    </a>
                                </div>
                                <button onclick="edit({{item.id}})" class="border-0 bg-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                                        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z" />
                                    </svg>
                                </button>
                                <form method="post">
                                    {% csrf_token %}
                                    <div>
                                        <button type="submit" class="border-0 bg-white">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z" />
                                                <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z" />
                                            </svg>
                                        </button>
                                    </div>
                                    <input type="hidden" name="form_type" value="delete">
                                    <input type="hidden" name="id_blog" value="{{item.id}}">
                                </form>
                            </div>
                        </div>
                        <div class="p-2 d-flex flex-column justify-content-between flex-fill">
                            <div>
                                <h1>{{ item.title }}</h1>
                                <div class="text-right">{{ item.created_at }}</div>
                                <div class="short-content mb-2">
                                    <span>{{ item.short_content }}</span>
                                </div>
                            </div>
                            <div>
                                Create by: {{ item.user }}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasRightLabel">Create Blog</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ form.title }}
            <div class="mb-3">
                {{ form.image }}
            </div>
            {{ form.short_content }}
            {{ form.content }}
            <input type="hidden" id="form_type" name="form_type" value="create">
            <input type="hidden" id="id" name="id" value="">
            <div class="d-flex gap-3">
                <button type="submit" class="btn btn-primary">Save</button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="offcanvas" aria-label="Close">Cancel</button>
            </div>
        </form>
    </div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script type="text/javascript">
function edit(id) {
    $("#offcanvasRightLabel").text("Update Blog")
    $("#form_type").val("edit-submit")
    $("#id").val(id)
    $.get(`/edit/blog/${id}`, function(data, status) {
        $("#id_title").val(data.context.title)
        $("#id_short_content").val(data.context.short_content)
        $("#id_content").val(data.context.content)
        $("#id_image").val(data.context.image)


    })
}

function createBlog() {

    $("#offcanvasRightLabel").text("Create Blog")
    $("#form_type").val("create")
}
</script>
{% endblock %}

ui/templates/home/home.html
{% extends 'layout.html'%}
{% block title %} Homepage {% endblock %}
{% load static %}
{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css'%}">
{% endblock %}
{% block content %}
<!-- banner -->
<div>
    <img src="https://nhatrangnow.com/wp-content/uploads/2022/05/PicsArt_08-25-09.22.38.jpg" class="banner">
</div>
<!-- item blog -->
<div class=" container py-5">
    <div class="row">
        {% if blog|length > 0 %}
        {% for item in blog %}
        <div class="col-4 pb-3">
            <div class="container-blog h-100 d-flex flex-column">
                <div>
                    <img src="{{ item.image }}" class="w-100 img-blog">
                </div>
                <div class="p-2 d-flex flex-column justify-content-between flex-fill">
                    <div>
                        <a href="{% url 'blog-detail' item.id %}">
                            <h1>{{ item.title }}</h1>
                        </a>
                        <div class="text-right">18/03/2024</div>
                        <div class="short-content mb-2">
                            <span>{{ item.short_content }}</span>
                        </div>
                    </div>
                    <div class="text-end px-2">
                        <a href="{% url 'blog-detail' item.id %}">Xem thêm</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-4 pb-3">
            <div class="container-blog h-100 d-flex flex-column">
                <div>
                    <img src="https://nhatrangnow.com/wp-content/uploads/2022/05/PicsArt_08-25-09.22.38.jpg" class="w-100 img-blog">
                </div>
                <div class="p-2 d-flex flex-column justify-content-between flex-fill">
                    <div>
                        <h1>Kinh nghiệm đi du lịch nha trang</h1>
                        <div class="text-right">18/03/2024</div>
                        <div class="short-content mb-2">
                            <span>Kinh nghiệm đi du lịch nha trang giành cho bạn, Kinh nghiệm đi du lịch nha trang giành cho bạn </span>
                        </div>
                    </div>
                    <div class="text-end px-2">
                        <a href="#" cl>Xem thêm</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4 pb-3">
            <div class="container-blog h-100 d-flex flex-column">
                <div>
                    <img src="https://nhatrangnow.com/wp-content/uploads/2022/05/PicsArt_08-25-09.22.38.jpg" class="w-100 img-blog">
                </div>
                <div class="p-2 d-flex flex-column justify-content-between flex-fill">
                    <div>
                        <h1>Kinh nghiệm đi du lịch nha trang</h1>
                        <div class="text-right">18/03/2024</div>
                        <div class="short-content mb-2">
                            <span>Kinh nghiệm đi du lịch nha trang giành cho bạn, Kinh nghiệm đi du lịch nha trang giành cho bạn </span>
                        </div>
                    </div>
                    <div class="text-end px-2">
                        <a href="#" cl>Xem thêm</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4 pb-3">
            <div class="container-blog h-100 d-flex flex-column">
                <div>
                    <img src="https://nhatrangnow.com/wp-content/uploads/2022/05/PicsArt_08-25-09.22.38.jpg" class="w-100 img-blog">
                </div>
                <div class="p-2 d-flex flex-column justify-content-between flex-fill">
                    <div>
                        <h1>Kinh nghiệm đi du lịch nha trang</h1>
                        <div class="text-right">18/03/2024</div>
                        <div class="short-content mb-2">
                            <span>Kinh nghiệm đi du lịch nha trang giành cho bạn, Kinh nghiệm đi du lịch nha trang giành cho bạn </span>
                        </div>
                    </div>
                    <div class="text-end px-2">
                        <a href="#" cl>Xem thêm</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4 pb-3">
            <div class="container-blog h-100 d-flex flex-column">
                <div>
                    <img src="https://nhatrangnow.com/wp-content/uploads/2022/05/PicsArt_08-25-09.22.38.jpg" class="w-100 img-blog">
                </div>
                <div class="p-2 d-flex flex-column justify-content-between flex-fill">
                    <div>
                        <h1>Kinh nghiệm đi du lịch nha trang</h1>
                        <div class="text-right">18/03/2024</div>
                        <div class="short-content mb-2">
                            <span>Kinh nghiệm đi du lịch nha trang giành cho bạn, Kinh nghiệm đi du lịch nha trang giành cho bạn </span>
                        </div>
                    </div>
                    <div class="text-end px-2">
                        <a href="#" cl>Xem thêm</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4 pb-3">
            <div class="container-blog h-100 d-flex flex-column">
                <div>
                    <img src="https://nhatrangnow.com/wp-content/uploads/2022/05/PicsArt_08-25-09.22.38.jpg" class="w-100 img-blog">
                </div>
                <div class="p-2 d-flex flex-column justify-content-between flex-fill">
                    <div>
                        <h1>Kinh nghiệm đi du lịch nha trang</h1>
                        <div class="text-right">18/03/2024</div>
                        <div class="short-content mb-2">
                            <span>Kinh nghiệm đi du lịch nha trang giành cho bạn, Kinh nghiệm đi du lịch nha trang giành cho bạn </span>
                        </div>
                    </div>
                    <div class="text-end px-2">
                        <a href="#" cl>Xem thêm</a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock%}

ui/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block static %} {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</head>

<body>
    <header class="header py-2 px-5">
        <div class="text-end">
            {% if user.is_authenticated %}
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-secondary">Log out</button>
            </form>
            {% else %}
            <a href="{% url 'login' %}">
                <button type="button" class="btn btn-secondary">Log in</button>
            </a>
            {% endif %}
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer></footer>
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>

</html>

ui/templates/login/login.html
{% extends 'layout.html' %}
{% block title %} Login {% endblock %}
{% load static %}
{% block static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css'%}">
{% endblock %}
{% block content %}
<div class="container-login">
    <form method="post" action="{% url 'login' %}">
      
        <div>
            {{ form.non_field_errors }}
            {% for field in form %}
            {{ field }}
            <div class="text-danger" style="font-size: 12px">{{ field.errors }}</div>
            <br>
            {% endfor %}
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-danger">Login</button>
              {% csrf_token %}
        </div>
    </form>
</div>
{% endblock %}

ui/templates/logout.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>

</body>
</html>